# Generated by Django 4.2.27 on 2026-02-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('blood_groups_needed', models.JSONField(default=list, help_text='List of blood groups needed')),
                ('expected_donors', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='accounts.campprofile')),
            ],
            options={
                'db_table': 'camps',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CampRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('units_needed', models.PositiveIntegerField()),
                ('units_collected', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='camp.camp')),
            ],
            options={
                'db_table': 'camp_requirements',
                'unique_together': {('camp', 'blood_group')},
            },
        ),
        migrations.CreateModel(
            name='CampAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('donation_time', models.DateTimeField(blank=True, null=True)),
                ('units_donated', models.PositiveIntegerField(default=0)),
                ('hemoglobin_level', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CHECKED_IN', 'Checked In'), ('DONATED', 'Donated'), ('DEFERRED', 'Deferred'), ('NO_SHOW', 'No Show')], default='REGISTERED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='camp.camp')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_donors', to=settings.AUTH_USER_MODEL)),
                ('donation_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_attendance', to='accounts.donorprofile')),
            ],
            options={
                'db_table': 'camp_attendance',
                'ordering': ['-created_at'],
                'unique_together': {('camp', 'donor')},
            },
        ),
    ]
