# Generated by Django 4.2.27 on 2026-02-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('units_needed', models.PositiveIntegerField()),
                ('request_type', models.CharField(choices=[('NORMAL', 'Normal'), ('EMERGENCY', 'Emergency'), ('DISASTER', 'Disaster')], default='NORMAL', max_length=20)),
                ('emergency_reason', models.TextField(blank=True)),
                ('required_by', models.DateTimeField()),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_contact', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_blood_requests', to='accounts.hospitalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_requests', to='accounts.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hospital_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_patient_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('units_requested', models.PositiveIntegerField()),
                ('units_approved', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('EMERGENCY', 'Emergency'), ('DISASTER', 'Disaster')], default='LOW', max_length=20)),
                ('required_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('providing_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_received', to='accounts.hospitalprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requesting_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_sent', to='accounts.hospitalprofile')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_requests_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_network',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('units_reserved', models.PositiveIntegerField(default=0)),
                ('expiry_alerts', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_stock', to='accounts.hospitalprofile')),
            ],
            options={
                'db_table': 'hospital_blood_stock',
                'unique_together': {('hospital', 'blood_group')},
            },
        ),
    ]
