# Generated by Django 4.2.27 on 2026-02-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('CAMP_APPROVAL', 'Camp Approval'), ('CAMP_REJECTION', 'Camp Rejection'), ('HOSPITAL_APPROVAL', 'Hospital Approval'), ('HOSPITAL_REJECTION', 'Hospital Rejection'), ('EMERGENCY_ALERT', 'Emergency Alert'), ('DISASTER_ALERT', 'Disaster Alert'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('BLOOD_REQUEST', 'Blood Request')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
