# Generated by Django 4.2.27 on 2026-02-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camp', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorHospitalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('units_needed', models.PositiveIntegerField()),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('EMERGENCY', 'Emergency'), ('DISASTER', 'Disaster')], default='LOW', max_length=20)),
                ('reason', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('required_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_alerts', to='accounts.hospitalprofile')),
            ],
            options={
                'db_table': 'donor_hospital_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('units_donated', models.PositiveIntegerField(default=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('hemoglobin_level', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='accounts.donorprofile')),
            ],
            options={
                'db_table': 'donation_history',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='DonorHospitalAlertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('GOOD', 'Good'), ('MINOR', 'Minor Issues')], max_length=10)),
                ('health_issues', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_responses', to='donor.donorhospitalalert')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_alert_responses', to='accounts.donorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donor_alert_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donor_hospital_alert_responses',
                'ordering': ['-responded_at'],
                'unique_together': {('alert', 'donor')},
            },
        ),
        migrations.CreateModel(
            name='CampApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('GOOD', 'Good'), ('MINOR', 'Minor Issues')], max_length=10)),
                ('health_issues', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='camp.camp')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_applications', to='accounts.donorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_camp_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camp_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('donor', 'camp')},
            },
        ),
    ]
